services:
  - type: static_site
    name: rapicredit-frontend
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
        headers:
          Cache-Control: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    environmentVariables:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://pagos-f2qf.onrender.com
