[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://pagos-f2qf.onrender.com"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

[context.production.environment]
  VITE_API_URL = "https://pagos-f2qf.onrender.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://pagos-f2qf.onrender.com"
