[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'postgresql']

[phases.install]
cmds = ['cd PAGOS && npm ci']

[phases.build]
cmds = ['cd PAGOS && npm run build']

[start]
cmd = 'cd PAGOS && npm run start'
