[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "cd backend && pip install --upgrade pip",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd backend && alembic upgrade head"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
