# backend/app/api/v1/endpoints/__init__.py
"""Endpoints de la API v1"""

# Importar todos los módulos de endpoints
from . import (
    amortizacion,
    analistas,
    aprobaciones,
    auditoria,
    auth,
    carga_masiva,
    clientes,
    cobranzas,
    concesionarios,
    conciliacion_bancaria,
    configuracion,
    dashboard,
    health,
    kpis,
    modelos_vehiculos,
    notificaciones,
    notificaciones_previas,
    pagos,
    pagos_conciliacion,
    pagos_upload,
    prestamos,
    reportes,
    scheduler_notificaciones,
    solicitudes,
    users,
    validadores,
    whatsapp_webhook,
)

__all__ = [
    "health",
    "auth",
    "users",
    "clientes",
    "concesionarios",
    "prestamos",
    "pagos",
    "amortizacion",
    "conciliacion_bancaria",
    "reportes",
    "kpis",
    "notificaciones",
    "notificaciones_previas",
    "aprobaciones",
    "auditoria",
    "configuracion",
    "dashboard",
    "analistas",
    "carga_masiva",
    "modelos_vehiculos",
    "solicitudes",
    "scheduler_notificaciones",
    "validadores",
    "cobranzas",
    "whatsapp_webhook",
]
