# backend/app/api/v1/endpoints/__init__.py
"""Endpoints de la API v1"""

# Importar todos los módulos de endpoints
from . import (  # aprobaciones,  # MODULO DESHABILITADO - Ver main.py
    ai_training,
    amortizacion,
    analistas,
    auditoria,
    auth,
    carga_masiva,
    clientes,
    cobranzas,
    concesionarios,
    conciliacion_bancaria,
    configuracion,
    conversaciones_whatsapp,
    dashboard,
    health,
    kpis,
    modelos_vehiculos,
    monitoring,
    notificaciones,
    notificaciones_dia_pago,
    notificaciones_prejudicial,
    notificaciones_previas,
    notificaciones_retrasadas,
    pagos,
    pagos_conciliacion,
    pagos_upload,
    prestamos,
    reportes,
    scheduler_notificaciones,
    solicitudes,
    tickets,
    users,
    validadores,
    whatsapp_webhook,
)

__all__ = [
    "ai_training",
    "health",
    "auth",
    "users",
    "clientes",
    "concesionarios",
    "prestamos",
    "pagos",
    "amortizacion",
    "conciliacion_bancaria",
    "reportes",
    "kpis",
    "notificaciones",
    "notificaciones_dia_pago",
    "notificaciones_prejudicial",
    "notificaciones_previas",
    "notificaciones_retrasadas",
    # "aprobaciones",  # MODULO DESHABILITADO
    "auditoria",
    "configuracion",
    "dashboard",
    "analistas",
    "carga_masiva",
    "modelos_vehiculos",
    "monitoring",
    "solicitudes",
    "scheduler_notificaciones",
    "validadores",
    "cobranzas",
    "whatsapp_webhook",
    "conversaciones_whatsapp",
    "tickets",
]
